kind: Secret
apiVersion: v1

metadata:
  name: secret
  namespace: bankapp-namespace

data: 
    MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Remove hard coded password 
    MYSQL_PASSWORD:  ${MYSQL_PASSWORD}  # Remove hard coded password 
    MYSQL_USER: ${MYSQL_USERNAME # Remove hard coded password 