kind: Secret
apiVersion: v1

metadata:
  name: secret
  namespace: bankapp-namespace

data:
  MYSQL_ROOT_PASSWORD: encode ur mysql root pass with base 64
  MYSQL_PASSWORD: encode ur mysql pass with base 64
  MYSQL_USER: encode your mysq user name with base 64
