kind: Secret
apiVersion: v1

metadata:
  name: secret
  namespace: bankapp-namespace

data: 
    MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    MYSQL_PASSWORD:  ${MYSQL_PASSWORD}
    MYSQL_USER: ${MYSQL_USERNAME}
 
