name: Packages-check
on: workflow_dispatch
jobs:
  packages_check_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v4

      - name: setup java-env
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "ai-bankapp-k8s"
          path: "."
          format: "HTML"
          # Set a threshold to fail the build if high-severity bugs are found
          args: >
            --failOnCVSS 7
            --enableRetired
