name: Packages-check
on: workflow_dispatch
jobs:
  packages_check_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v4

      - name: setup java-env
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Build
        run: mvn clean install -DskipTests

      - name: Cache OWASP NVD Database
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: owasp-nvd-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            owasp-nvd-${{ runner.os }}-

      - name: Run OWASP Dependency Check
        run: |
          mvn org.owasp:dependency-check-maven:check \
          -Dnvd.apiKey=${{ secrets.NVD_API_KEY }}
