name: Trivy image scan
on: 
    workflow_dispatch
jobs: 
    Trivy_scan:
        runs-on: ubuntu-latest
        steps: 
            - name: code-checkout
              uses: actions/checkout@v4


            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                java-version: '21' 
                distribution: 'temurin'
                cache: maven

            - name: Build Jar with Maven
              run: mvn clean package -DskipTests



            - name: Build Docker Image
              run: |
               docker build -t harsh9308/bank-app-devsecops:${{ github.sha }} .



            - name: Run trivi scan
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: docker build -t harsh9308/bank-app-devsecops:${{ github.sha }}
                severity: "HIGH"
                exit-code: 1